name: sdkgen_runtime
version: 0.0.0
homepage: https://sdkgen.github.io/
description: Dart API client for sdkgen server. It must be used with a generated file, see docs.

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  convert: ^3.0.0
  decimal: ^2.2.0
  device_info_plus: ^4.0.0
  equatable: ^2.0.0
  http: ^0.13.0
  package_info: ^2.0.0
  shared_preferences: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.0
  test: ">=1.16.0 <2.0.0"
  flutter_test:
    sdk: flutter
