name: sdkgen_runtime
version: 0.0.0
homepage: https://sdkgen.github.io/
description: Dart API client for sdkgen server. It must be used with a generated file, see docs.

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  convert: ^3.1.1
  decimal: ^2.3.2
  device_info_plus: ^9.0.1
  equatable: ^2.0.5
  http: ^1.0.0
  package_info_plus: ^4.0.2
  shared_preferences: ^2.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.1
  test: ">=1.21.1 <2.0.0"
  flutter_test:
    sdk: flutter
